### ISSUE TITLE
Fragmentuak ez egin commit edozein momentutan

### ISSUE THREAD

**Issue by 9and3r** [9and3r/livetracking#37]
- [x] Mobileko bertsioan live track eremua aldatu viewak ezkutatuz
- [x] Wear bertsioan ere aldatu berdina lortzeko
- [x] Mobileko bertsioan aldaketa egitean fragmentu guztien aukerak daude. Adibidez track bat ez da hasi eta ondorioz new track fragmentua dago baina inivisible moduan dagoenez mapa ere mapa aldatzeko botoia agertzen da.

**Comment by aorbegozo005** [comment]
#32 rekin lotuta dago
